language: node_js
node_js:
  - "0.10"
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "wget https://raw.github.com/arunoda/travis-ci-meteor-packages/master/start_test.js"
  - "wget https://raw.github.com/arunoda/travis-ci-meteor-packages/master/phantom_runner.js"
script:
  make all
